apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - type: Pod
      min:
        cpu: 50m
        memory: 26Mi
      max: 
        cpu: "2"
        memory: 2Gi
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 26Mi
      default: 
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 50m
        memory: 26Mi
      max:
        cpu: "1"
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: "3"
        memory: 26Mi
    - type: PersistentVolumeClaim
      min: 
        storage: 1Gi
      max:
        storage: 5Gi
