apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-demo
  name: resource-demo
spec:
  containers:
  - command:
    - stress
    args:
    - --cpu
    - "2"
    - --vm
    - "1"
    - --vm-bytes
    - 1G
    - --vm-hang
    - "1"
    image: polinux/stress
    name: resource-demo
    resources: 
      requests:
        cpu: "10m"
        memory: "500Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
