apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-demo
  name: resource-demo
spec:
  containers:
  - command:
    - stress
    - cpu="1"
    - vm=1
    - vm-bytes=1G
    - vm-hang=1
    image: polinux/stress
    name: resource-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
