apiVersion: v1
kind: Service
metadata:
  name: mongo-headlessvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  ClusterIp: None # Becomes Headless service
