apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.nginx.kubernetes.io/redirect: /
  creationTimestamp: null
  name: simple-ingress
spec:
  ingressClassName: default
  rules:
  - host: flaskdemo.com
    http:
      paths:
      - backend:
          service:
            name: svc-clusterip
            port:
              number: 5000
        path: /
        pathType: Prefix
