apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: flaskdemo
  type: NodePort
status:
  loadBalancer: {}
